### ISSUE TITLE
I use the gym 0.19.0 nut it has wrongs whch says "No registered env with id: halfcheetah-medium-expert-v2"

### ISSUE THREAD

**Issue by 97979797** [jannerm/diffuser#49]
Traceback (most recent call last):
  File "scripts/plan_guided.py", line 26, in <module>
    diffusion_experiment = utils.load_diffusion(
  File "/home/leon/leon_ws/diffuser-main/diffuser/utils/serialization.py", line 47, in load_diffusion
    dataset = dataset_config(seed=seed)
  File "/home/leon/leon_ws/diffuser-main/diffuser/utils/config.py", line 65, in __call__
    instance = self._class(*args, **kwargs, **self._dict)
  File "/home/leon/leon_ws/diffuser-main/diffuser/datasets/sequence.py", line 22, in __init__
    self.env = env = load_environment(env)
  File "/home/leon/leon_ws/diffuser-main/diffuser/datasets/d4rl.py", line 36, in load_environment
    wrapped_env = gym.make(name)
  File "/home/leon/leon_ws/diffuser-main/gym/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/home/leon/leon_ws/diffuser-main/gym/gym/envs/registration.py", line 89, in make
    spec = self.spec(path)
  File "/home/leon/leon_ws/diffuser-main/gym/gym/envs/registration.py", line 131, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: halfcheetah-medium-expert-v2

**Comment by wen1tao1** [comment]
Me,too

**Comment by wen1tao1** [comment]
> Traceback (most recent call last): File "scripts/plan_guided.py", line 26, in diffusion_experiment = utils.load_diffusion( File "/home/leon/leon_ws/diffuser-main/diffuser/utils/serialization.py", line 47, in load_diffusion dataset = dataset_config(seed=seed) File "/home/leon/leon_ws/diffuser-main/diffuser/utils/config.py", line 65, in **call** instance = self._class(*args, **kwargs, **self._dict) File "/home/leon/leon_ws/diffuser-main/diffuser/datasets/sequence.py", line 22, in **init** self.env = env = load_environment(env) File "/home/leon/leon_ws/diffuser-main/diffuser/datasets/d4rl.py", line 36, in load_environment wrapped_env = gym.make(name) File "/home/leon/leon_ws/diffuser-main/gym/gym/envs/registration.py", line 145, in make return registry.make(id, **kwargs) File "/home/leon/leon_ws/diffuser-main/gym/gym/envs/registration.py", line 89, in make spec = self.spec(path) File "/home/leon/leon_ws/diffuser-main/gym/gym/envs/registration.py", line 131, in spec raise error.UnregisteredEnv('No registered env with id: {}'.format(id)) gym.error.UnregisteredEnv: No registered env with id: halfcheetah-medium-expert-v2

Did you solve this problem?

**Comment by HuangDou228** [comment]
Hello there,
I have tried modify diffuser/environments/registration.py, in which I added following code in `ENVIRONMENT_SPECS=`
` {
        'id':'halfcheetah-medium-expert-v2',
        'entry_point':('diffuser.environments.half_cheetah:HalfCheetahFullObsEnv'),
    },`
This solved the problem of "No registered env with id: halfcheetah-medium-expert-v2". 

However, when I run plan_guided.py again, it comes out with new error.
`AttributeError: attempted to get missing private attribute '_max_episode_steps'`

I hope this method could be helpful to this problem, and also hope someone could fix the new error.
