### ISSUE TITLE
error in kuka branch

### ISSUE THREAD

**Issue by ekkooee7** [jannerm/diffuser#57]
Hey, thanks for your amazing jobs!

I met some problem when I'm trying to run 
`python scripts/unconditional_kuka_planning_eval.py`

The following error raised:

```
Traceback (most recent call last):
  File "scripts/unconditional_kuka_planning_eval.py", line 220, in <module>
    dataset = KukaDataset(H)
  File "/home/waz/workspace/diffuser/denoising_diffusion_pytorch/datasets/tamp.py", line 143, in __init__
    qstates = qstates[:i+1]
UnboundLocalError: local variable 'i' referenced before assignment
```

Is there any mistake about the code?

**Comment by HaoranZhangumich** [comment]
same problem here. It seems because there is no kuka_dataset/*.npy

**Comment by yilundu** [comment]
Can you download the data at this [URL](https://www.dropbox.com/scl/fi/2mw1h5hbzzlh4mj8v6mnt/metainfo.tar.gz?rlkey=k7lovhb93kdcih7474gng4lgl&e=1&dl=0)?

**Comment by HaoranZhangumich** [comment]
Thanks! But, I still got the same issue after I download the dataset when I am trying to run scripts/kuka.py.

**Comment by WimerLeijendekker** [comment]
You have to make sure that the kuka_dataset folder is directly in the root directory of the repo and not within the metainfo folder. If it does not find this folder, the dataset will remain empty and it won't set 'i'.
